# Generated by Django 2.2.4 on 2021-01-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt3_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='first_name',
            new_name='task',
        ),
    ]
